# Generated by Django 3.2.8 on 2022-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Ratings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reviews', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
    ]
