# Generated by Django 4.0 on 2022-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Ratings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reviews', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JsonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='file_media/')),
            ],
        ),
    ]
