# Generated by Django 4.0 on 2022-08-03 05:19

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_jsonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='upload_file',
            field=models.FileField(storage=myapp.models.OverwriteStorage(), upload_to='file_media/'),
        ),
    ]
